[package]
name = "rust-block-cache"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_block_cache"

[[bin]]
name = "example"
path = "src/main.rs"

[dependencies]
chrono = "0.4.42"
indexmap = "2.11.4"
arc-swap = "1.7"
timer = "0.2.0"
